"""add execution_date to dag_runs

Revision ID: 39ccc74022ac
Revises: 6a6a4cd6d2a7
Create Date: 2026-06-12 04:51:07.334561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ccc74022ac'
down_revision: Union[str, Sequence[str], None] = '6a6a4cd6d2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
